//This c++ code is generated by PictoBlox

#include <evive.h>

//Included Libraries
#include <Adafruit_NeoPixel.h>

//MACROS are defined here
TFT_ST7735 lcd = TFT_ST7735();
Adafruit_NeoPixel Strip_1 = Adafruit_NeoPixel(86, 2, NEO_GRB + NEO_KHZ800);
double currentTime1 = 0;
double lastTime1 = 0;
double getLastTime(){
		return currentTime1 = millis()/1000.0 - lastTime1;
}
Motor Motor1(MOTOR1_D1, MOTOR1_D2, MOTOR1_EN);

//Gloabl Variables are declared here
float Game_State;
float Current_Time;
float Last_Time;
float Score;

//User Defined Functions
void Initialisation() {
	lcd.fillScreen(0);
	Game_State = 1;
	Current_Time = 0;
	Last_Time = 0;
	Score = 0;
	lcd.fillRoundRect(30, 30, 110, 80, 5, 65535);
	lcd.setCursor(60, 40);
	lcd.setTextColor(63488, 0);
	lcd.setTextSize(1);
	lcd.print("SCORE");
}
void Game_Start() {
	if((Game_State == 0)) {
		Flipper_Control();
		Strip_1.pattern1(1, Strip_1.ColorString("0025bd"), 0.01*1000);
		lcd.print((Score + ((int) getLastTime())));
		if(((digitalRead(2) == 0) && (digitalRead(2) == 0))) {
			Score += (Score + 50);
			Score = Score;
		}
		else {
			if((digitalRead(2) == 0)) {
				Score += (Score + 100);
				Score = Score;
			}
			else {
				if((digitalRead(2) == 0)) {
					Game_Over();
				}
			}
		}
	}
}
void Flipper_Control() {
	if((digitalRead(2) == 0)) {
		while(!(digitalRead(2) == 0)) {
			Motor1.moveMotor(2.55*100);
		}
		Motor1.freeMotor();
		delay(0.01 * 1000);
		while(!(digitalRead(2) == 0)) {
			Motor1.moveMotor(2.55*100);
		}
		Motor1.freeMotor();
	}
	if((digitalRead(2) == 0)) {
		while(!(digitalRead(2) == 0)) {
			Motor1.moveMotor(2.55*100);
		}
		Motor1.freeMotor();
		delay(0.01 * 1000);
		while(!(digitalRead(2) == 0)) {
			Motor1.moveMotor(2.55*100);
		}
		Motor1.freeMotor();
	}
}
void Game_Over() {
	Strip_1.pattern1(1, Strip_1.ColorString("445abd"), 0.01*1000);
	lcd.setCursor(60, 100);
	lcd.print((Score + ((int) getLastTime())));
	lcd.setCursor(60, 80);
	lcd.setTextColor(57539, 0);
	lcd.setTextSize(1);
	lcd.print("GAME OVER");
	Game_State = 1;
}

void setup() {
	//put your setup code here, to run once:
	lcd.init(INITR_BLACKTAB);
	lcd.setRotation(1);
	Strip_1.begin();
	 Strip_1.show();
	pinMode(2, INPUT);
	
	
	Initialisation();
}

void loop() {
	//put your main code here, to run repeatedly:
	
	
	lcd.setCursor(60, 60);
	lcd.setTextColor(5248, 0);
	lcd.setTextSize(1);
	if((digitalRead(2) == 0)) {
		Last_Time = getLastTime();
		Game_State = 0;
		Score = 0;
	}
	Game_Start();
}
